import { initialDemoData } from '@/data/demo-data'
import { calculateScore, canStartAttempt, isPassed, shouldUnlockReview } from '@/features/exam/engine'
import { isSupabaseConfigured, supabase } from '@/lib/supabase'
import type { AppData, Attempt, AttemptQuestion, Employee, LearnerState, PublicBatchSummary } from '@/types/domain'
const STORAGE_KEY = 'tlp-training-demo-v1'
function read(): AppData { try { const raw = localStorage.getItem(STORAGE_KEY); return raw ? JSON.parse(raw) as AppData : structuredClone(initialDemoData) } catch { return structuredClone(initialDemoData) } }
function write(data: AppData) { localStorage.setItem(STORAGE_KEY, JSON.stringify(data)) }
function key(batchId: string, employeeId: string) { return `${batchId}:${employeeId}` }
function randomize<T>(items: T[]) { const copy = [...items]; for (let index = copy.length - 1; index > 0; index--) { const target = Math.floor(Math.random() * (index + 1)); [copy[index], copy[target]] = [copy[target], copy[index]] } return copy }
function publicAttempt(attempt: Attempt): Attempt { return { ...attempt, questions: attempt.questions.map((question) => ({ ...question, explanation: attempt.reviewUnlocked ? question.explanation : undefined, options: question.options.map((option) => ({ ...option, isCorrect: attempt.reviewUnlocked ? option.isCorrect : undefined })) })) } }

async function rpc<T>(name: string, args: Record<string, unknown>) { if (!supabase) throw new Error('Supabase chưa cấu hình.'); const { data, error } = await supabase.rpc(name, args); if (error) throw error; return data as T }
export const learnerService = {
  async getPublicBatch(publicToken: string): Promise<PublicBatchSummary> {
    if (isSupabaseConfigured) return rpc('get_public_batch', { p_public_token: publicToken })
    const data = read(); const batch = data.batches.find((item) => item.publicToken === publicToken); if (!batch) throw new Error('Link đào tạo không tồn tại.'); const course = data.courses.find((item) => item.id === batch.courseId)
    return { batchId: batch.id, batchName: batch.batchName, courseName: course?.courseName ?? '', startAt: batch.startAt, dueAt: batch.dueAt, status: batch.status }
  },
  async searchEmployees(publicToken: string, query: string): Promise<Employee[]> {
    if (isSupabaseConfigured) return rpc('search_batch_employees', { p_public_token: publicToken, p_query: query })
    const data = read(); const batch = data.batches.find((item) => item.publicToken === publicToken); if (!batch) return []; const normalized = query.trim().toLowerCase(); return data.employees.filter((employee) => batch.employeeIds.includes(employee.id) && employee.isActive && (!normalized || `${employee.employeeCode} ${employee.fullName}`.toLowerCase().includes(normalized))).slice(0, 20)
  },
  async getState(publicToken: string, employeeId: string): Promise<LearnerState> {
    if (isSupabaseConfigured) return rpc('get_learner_state', { p_public_token: publicToken, p_employee_id: employeeId })
    let data = read(); const batch = data.batches.find((item) => item.publicToken === publicToken); const employee = data.employees.find((item) => item.id === employeeId); if (!batch || !employee || !batch.employeeIds.includes(employeeId)) throw new Error('Nhân viên không thuộc đợt đào tạo này.'); const expired = data.attempts.find((attempt) => attempt.batchId === batch.id && attempt.employeeId === employeeId && attempt.status === 'IN_PROGRESS' && new Date(attempt.deadlineAt).getTime() <= Date.now()); if (expired) { await this.submitAttempt(publicToken, employeeId, expired.id, true); data = read() }
    const course = data.courses.find((item) => item.id === batch.courseId); if (!course) throw new Error('Không tìm thấy khóa đào tạo.'); const completedIds = data.materialProgress[key(batch.id, employeeId)] ?? []; const materials = data.materials.filter((item) => item.courseId === course.id && item.isActive).map((item) => ({ ...item, completed: completedIds.includes(item.id) })); const attempts = data.attempts.filter((attempt) => attempt.batchId === batch.id && attempt.employeeId === employeeId).sort((a, b) => a.attemptNo - b.attemptNo); const materialComplete = materials.filter((item) => item.isRequired).every((item) => item.completed); const rule = canStartAttempt({ attemptsUsed: attempts.length, maxAttempts: batch.maxAttempts, alreadyPassed: attempts.some((item) => item.passed), stopOnPass: batch.stopOnPass, materialComplete, requireMaterialCompletion: batch.requireMaterialCompletion, batchStatus: batch.status, now: Date.now(), startAt: batch.startAt ? new Date(batch.startAt).getTime() : null, dueAt: batch.dueAt ? new Date(batch.dueAt).getTime() : null }); const active = attempts.find((item) => item.status === 'IN_PROGRESS')
    return { batch, employee, course, materials, attempts: attempts.map(publicAttempt), attemptsUsed: attempts.length, attemptsRemaining: Math.max(0, batch.maxAttempts - attempts.length), bestScore: attempts.reduce<number | null>((best, item) => item.scorePercent == null ? best : best == null ? item.scorePercent : Math.max(best, item.scorePercent), null), lastScore: attempts.at(-1)?.scorePercent ?? null, activeAttemptId: active?.id ?? null, canStart: Boolean(active) || rule.allowed, reason: active ? null : rule.reason }
  },
  async markMaterialComplete(publicToken: string, employeeId: string, materialId: string) {
    if (isSupabaseConfigured) { await rpc('mark_material_completed', { p_public_token: publicToken, p_employee_id: employeeId, p_material_id: materialId }); return }
    const data = read(); const batch = data.batches.find((item) => item.publicToken === publicToken); if (!batch || !data.materials.some((item) => item.id === materialId && item.courseId === batch.courseId)) throw new Error('Tài liệu không hợp lệ.'); const progressKey = key(batch.id, employeeId); data.materialProgress[progressKey] = Array.from(new Set([...(data.materialProgress[progressKey] ?? []), materialId])); write(data)
  },
  async startOrResume(publicToken: string, employeeId: string): Promise<Attempt> {
    if (isSupabaseConfigured) return rpc('start_or_resume_attempt', { p_public_token: publicToken, p_employee_id: employeeId })
    const state = await this.getState(publicToken, employeeId); const data = read(); const active = data.attempts.find((item) => item.id === state.activeAttemptId); if (active) return publicAttempt(active); if (!state.canStart) throw new Error(state.reason ?? 'Không thể bắt đầu bài thi.'); const exam = data.exams.find((item) => item.id === state.batch.examId); const bank = data.banks.find((item) => item.id === exam?.bankId); if (!exam || !bank) throw new Error('Cấu hình bài thi không hợp lệ.'); const source = exam.selectionMode === 'RANDOM' ? randomize(bank.questions.filter((item) => item.isActive)).slice(0, state.batch.questionCount) : bank.questions.filter((item) => item.isActive).slice(0, state.batch.questionCount); const ordered = state.batch.shuffleQuestions ? randomize(source) : source; const questions: AttemptQuestion[] = ordered.map((question, index) => ({ id: crypto.randomUUID(), displayOrder: index + 1, text: question.questionText, explanation: question.explanation, points: question.defaultPoints, options: (state.batch.shuffleOptions ? randomize(question.options) : question.options).map((option, optionIndex) => ({ id: crypto.randomUUID(), displayOrder: optionIndex + 1, text: option.optionText, isCorrect: option.isCorrect })) })); const startedAt = new Date(); const attempt: Attempt = { id: crypto.randomUUID(), employeeId, batchId: state.batch.id, attemptNo: state.attemptsUsed + 1, startedAt: startedAt.toISOString(), deadlineAt: new Date(startedAt.getTime() + state.batch.timeLimitMinutes * 60_000).toISOString(), submittedAt: null, durationSeconds: null, status: 'IN_PROGRESS', scorePercent: null, passed: null, autoSubmitted: false, reviewUnlocked: false, questions }; data.attempts.push(attempt); const batch = data.batches.find((item) => item.id === state.batch.id); const learner = batch?.learnerStates.find((item) => item.employeeId === employeeId); if (learner) { learner.currentStatus = 'IN_PROGRESS'; learner.attemptsUsed = attempt.attemptNo; learner.lastAttemptAt = startedAt.toISOString() } write(data); return publicAttempt(attempt)
  },
  async saveAnswer(publicToken: string, employeeId: string, attemptId: string, questionId: string, optionId: string) {
    if (isSupabaseConfigured) { await rpc('save_answer', { p_public_token: publicToken, p_employee_id: employeeId, p_attempt_id: attemptId, p_attempt_question_id: questionId, p_attempt_option_id: optionId }); return }
    const data = read(); const batch = data.batches.find((item) => item.publicToken === publicToken); const attempt = data.attempts.find((item) => item.id === attemptId && item.employeeId === employeeId && item.batchId === batch?.id && item.status === 'IN_PROGRESS'); const question = attempt?.questions.find((item) => item.id === questionId); if (!attempt || !question || !question.options.some((item) => item.id === optionId)) throw new Error('Đáp án không hợp lệ.'); question.selectedOptionId = optionId; write(data)
  },
  async submitAttempt(publicToken: string, employeeId: string, attemptId: string, autoSubmitted = false): Promise<Attempt> {
    if (isSupabaseConfigured) return rpc('submit_attempt', { p_public_token: publicToken, p_employee_id: employeeId, p_attempt_id: attemptId, p_auto_submitted: autoSubmitted })
    const data = read(); const batch = data.batches.find((item) => item.publicToken === publicToken); const attempt = data.attempts.find((item) => item.id === attemptId && item.employeeId === employeeId && item.batchId === batch?.id); if (!batch || !attempt) throw new Error('Attempt không hợp lệ.'); if (attempt.status === 'SUBMITTED') return publicAttempt(attempt); const score = calculateScore(attempt.questions); attempt.status = 'SUBMITTED'; attempt.submittedAt = new Date().toISOString(); attempt.durationSeconds = Math.max(0, Math.round((new Date(attempt.submittedAt).getTime() - new Date(attempt.startedAt).getTime()) / 1000)); attempt.scorePercent = score.scorePercent; attempt.passed = isPassed(score.scorePercent, batch.passScore); attempt.autoSubmitted = autoSubmitted; attempt.reviewUnlocked = shouldUnlockReview(batch.reviewPolicy, attempt.passed, batch.stopOnPass, attempt.attemptNo, batch.maxAttempts); const learner = batch.learnerStates.find((item) => item.employeeId === employeeId); if (learner) { learner.attemptsUsed = attempt.attemptNo; learner.lastScore = score.scorePercent; learner.bestScore = Math.max(learner.bestScore ?? 0, score.scorePercent); learner.lastAttemptAt = attempt.submittedAt; learner.currentStatus = attempt.passed ? (batch.stopOnPass ? 'PASSED' : 'READY_FOR_EXAM') : attempt.attemptNo >= batch.maxAttempts ? 'FAILED' : 'READY_FOR_EXAM'; if (attempt.passed) learner.completedAt = attempt.submittedAt } write(data); return publicAttempt(attempt)
  },
}
