import { useCallback, useEffect, useMemo, useState } from 'react'
import { useParams } from 'react-router-dom'
import { Check, CheckCircle2, ChevronLeft, ChevronRight, Clock3, LoaderCircle, Search, ShieldCheck, XCircle } from 'lucide-react'
import { learnerService } from '@/features/learner/learner-service'; import { remainingSeconds } from '@/features/exam/engine'; import type { Attempt, Employee, LearnerState, PublicBatchSummary } from '@/types/domain'; import { Button } from '@/components/ui/button'; import { Input } from '@/components/ui/input'; import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'; import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog'; import { ErrorState, LoadingState } from '@/components/ui/state'; import { formatDate, formatScore } from '@/lib/utils'
type Stage = 'SELECT' | 'HOME' | 'EXAM' | 'RESULT'
export default function LearnerPage() {
  const { publicToken = '' } = useParams(); const [batch, setBatch] = useState<PublicBatchSummary | null>(null); const [employee, setEmployee] = useState<Employee | null>(null); const [state, setState] = useState<LearnerState | null>(null); const [attempt, setAttempt] = useState<Attempt | null>(null); const [stage, setStage] = useState<Stage>('SELECT'); const [loading, setLoading] = useState(true); const [error, setError] = useState('')
  const loadState = useCallback(async (selected: Employee) => { const next = await learnerService.getState(publicToken, selected.id); setState(next); const latest = next.attempts.at(-1); if (next.activeAttemptId) { const active = await learnerService.startOrResume(publicToken, selected.id); setAttempt(active); setStage('EXAM') } else if (latest?.status === 'SUBMITTED') { setAttempt(latest); setStage('RESULT') } else setStage('HOME') }, [publicToken])
  useEffect(() => { let alive = true; learnerService.getPublicBatch(publicToken).then(async (summary) => { if (!alive) return; setBatch(summary); const employeeId = sessionStorage.getItem(`tlp-learner:${publicToken}`); if (employeeId) { const matches = await learnerService.searchEmployees(publicToken, ''); const selected = matches.find((item) => item.id === employeeId); if (selected) { setEmployee(selected); await loadState(selected) } } }).catch((reason: unknown) => setError(reason instanceof Error ? reason.message : 'Không thể tải đợt đào tạo.')).finally(() => setLoading(false)); return () => { alive = false } }, [publicToken, loadState])
  async function choose(selected: Employee) { setEmployee(selected); sessionStorage.setItem(`tlp-learner:${publicToken}`, selected.id); setLoading(true); setError(''); try { await loadState(selected) } catch (reason) { setError(reason instanceof Error ? reason.message : 'Không thể tải trạng thái người học.') } finally { setLoading(false) } }
  async function refresh() { if (!employee) return; setLoading(true); try { await loadState(employee) } finally { setLoading(false) } }
  if (loading) return <LearnerShell><LoadingState label="Đang tải chương trình đào tạo…" /></LearnerShell>
  if (error || !batch) return <LearnerShell><ErrorState message={error || 'Không tìm thấy đợt đào tạo.'} /></LearnerShell>
  return <LearnerShell>{stage === 'SELECT' ? <EmployeeSelection batch={batch} token={publicToken} onChoose={choose} /> : null}{stage === 'HOME' && state && employee ? <LearnerHome state={state} onComplete={async (materialId) => { await learnerService.markMaterialComplete(publicToken, employee.id, materialId); await refresh() }} onStart={async () => { setLoading(true); try { const next = await learnerService.startOrResume(publicToken, employee.id); setAttempt(next); setStage('EXAM') } catch (reason) { setError(reason instanceof Error ? reason.message : 'Không thể bắt đầu bài thi.') } finally { setLoading(false) } }} onChangeEmployee={() => { setStage('SELECT'); setEmployee(null); sessionStorage.removeItem(`tlp-learner:${publicToken}`) }} /> : null}{stage === 'EXAM' && attempt && employee ? <ExamScreen attempt={attempt} onSave={(questionId, optionId) => learnerService.saveAnswer(publicToken, employee.id, attempt.id, questionId, optionId)} onSubmit={async (auto) => { const result = await learnerService.submitAttempt(publicToken, employee.id, attempt.id, auto); setAttempt(result); setState(await learnerService.getState(publicToken, employee.id)); setStage('RESULT') }} /> : null}{stage === 'RESULT' && attempt && state ? <ResultScreen attempt={attempt} state={state} onRetry={async () => { const next = await learnerService.startOrResume(publicToken, state.employee.id); setAttempt(next); setStage('EXAM') }} onHome={() => setStage('HOME')} /> : null}</LearnerShell>
}
function LearnerShell({ children }: { children: React.ReactNode }) { return <main className="min-h-screen bg-slate-100 px-4 py-6 sm:py-10"><div className="mx-auto max-w-2xl"><div className="mb-5 flex items-center gap-3"><div className="grid size-10 place-items-center rounded-md bg-[#071d35] font-extrabold text-white">TLP</div><div><p className="font-bold">TLP Training</p><p className="text-xs text-muted-foreground">Cổng đào tạo dành cho nhân viên</p></div></div>{children}</div></main> }
function EmployeeSelection({ batch, token, onChoose }: { batch: PublicBatchSummary; token: string; onChoose: (employee: Employee) => void }) {
  const [query, setQuery] = useState(''); const [rows, setRows] = useState<Employee[]>([]); const [selected, setSelected] = useState<Employee | null>(null); const [busy, setBusy] = useState(false)
  useEffect(() => { const handle = setTimeout(() => { setBusy(true); learnerService.searchEmployees(token, query).then(setRows).finally(() => setBusy(false)) }, 200); return () => clearTimeout(handle) }, [query, token])
  return <Card><CardHeader><CardTitle className="text-2xl">{batch.batchName}</CardTitle><CardDescription>{batch.courseName} · Hạn {formatDate(batch.dueAt)}</CardDescription></CardHeader><CardContent><h2 className="mb-3 text-lg font-semibold">Chọn nhân viên</h2><label className="relative block"><Search className="absolute left-3 top-3 text-muted-foreground" /><Input className="h-12 pl-10" placeholder="Tìm theo mã hoặc họ tên" value={query} onChange={(event) => setQuery(event.target.value)} /></label><div className="mt-3 max-h-72 overflow-y-auto rounded-md border">{busy ? <p className="p-4 text-sm text-muted-foreground">Đang tìm…</p> : rows.length === 0 ? <p className="p-4 text-sm text-muted-foreground">Không tìm thấy nhân viên trong đợt này.</p> : rows.map((employee) => <button key={employee.id} className={`flex w-full items-center gap-3 border-b p-4 text-left last:border-0 ${selected?.id === employee.id ? 'bg-blue-50 text-primary' : 'hover:bg-muted'}`} onClick={() => setSelected(employee)}><span className={`grid size-5 place-items-center rounded-full border ${selected?.id === employee.id ? 'border-primary bg-primary text-white' : ''}`}>{selected?.id === employee.id ? <Check /> : null}</span><span className="font-medium">{employee.employeeCode} — {employee.fullName}</span></button>)}</div><Button size="lg" className="mt-6 w-full" disabled={!selected} onClick={() => selected && onChoose(selected)}>Tiếp tục</Button><p className="mt-3 text-center text-xs text-muted-foreground">MVP không yêu cầu đăng nhập, PIN hoặc OTP.</p></CardContent></Card>
}
function LearnerHome({ state, onComplete, onStart, onChangeEmployee }: { state: LearnerState; onComplete: (id: string) => Promise<void>; onStart: () => void; onChangeEmployee: () => void }) {
  const requiredDone = state.materials.filter((item) => item.isRequired).every((item) => item.completed)
  return <div className="flex flex-col gap-5"><Card><CardHeader><CardTitle>{state.batch.batchName}</CardTitle><CardDescription>{state.employee.employeeCode} — {state.employee.fullName}</CardDescription></CardHeader><CardContent><div className="grid grid-cols-2 gap-3 text-sm sm:grid-cols-4"><Info label="Số câu" value={`${state.batch.questionCount}`} /><Info label="Thời gian" value={`${state.batch.timeLimitMinutes} phút`} /><Info label="Điểm đạt" value={`${state.batch.passScore}%`} /><Info label="Còn lại" value={`${state.attemptsRemaining} lượt`} /></div></CardContent></Card>{state.materials.map((material) => <Card key={material.id}><CardHeader><CardTitle className="text-lg">{material.title}</CardTitle><CardDescription>{material.estimatedMinutes} phút · {material.isRequired ? 'Bắt buộc' : 'Tùy chọn'}</CardDescription></CardHeader><CardContent><p className="whitespace-pre-line text-sm leading-7 text-slate-700">{material.content}</p><Button className="mt-5" variant={material.completed ? 'secondary' : 'default'} disabled={material.completed} onClick={() => onComplete(material.id)}>{material.completed ? <CheckCircle2 /> : null}{material.completed ? 'Đã hoàn thành' : 'Đánh dấu đã đọc'}</Button></CardContent></Card>)}<Card><CardContent className="p-5"><div className="flex items-start gap-3"><ShieldCheck className="mt-0.5 text-primary" /><div><p className="font-semibold">Trước khi bắt đầu</p><p className="mt-1 text-sm text-muted-foreground">Timer được lưu theo thời gian bắt đầu trên hệ thống. Tải lại trang không làm tăng lượt hoặc reset thời gian.</p><p className="mt-2 text-xs text-muted-foreground">Chính sách đáp án: {state.batch.reviewPolicy === 'AFTER_EACH_SUBMISSION' ? 'Xem sau mỗi lần nộp' : 'Chỉ xem sau khi khóa lượt cuối'}</p></div></div>{!state.canStart ? <p className="mt-4 rounded-md bg-amber-50 p-3 text-sm text-amber-700">{state.reason}</p> : null}<Button size="lg" className="mt-5 w-full" disabled={!state.canStart || (state.batch.requireMaterialCompletion && !requiredDone)} onClick={onStart}>{state.activeAttemptId ? 'Tiếp tục bài đang làm' : 'Bắt đầu kiểm tra'}</Button><Button variant="ghost" className="mt-2 w-full" onClick={onChangeEmployee}>Chọn nhân viên khác</Button></CardContent></Card></div>
}
function Info({ label, value }: { label: string; value: string }) { return <div className="rounded-md bg-muted p-3"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 font-bold">{value}</p></div> }
function ExamScreen({ attempt, onSave, onSubmit }: { attempt: Attempt; onSave: (questionId: string, optionId: string) => Promise<void>; onSubmit: (auto: boolean) => Promise<void> }) {
  const [questions, setQuestions] = useState(attempt.questions); const [index, setIndex] = useState(0); const [remaining, setRemaining] = useState(() => remainingSeconds(attempt.deadlineAt)); const [confirm, setConfirm] = useState(false); const [submitting, setSubmitting] = useState(false); const question = questions[index]
  const submit = useCallback(async (auto: boolean) => { setSubmitting(true); try { await onSubmit(auto) } finally { setSubmitting(false) } }, [onSubmit])
  useEffect(() => { const timer = window.setInterval(() => { const next = remainingSeconds(attempt.deadlineAt); setRemaining(next); if (next === 0) { window.clearInterval(timer); void submit(true) } }, 1000); return () => window.clearInterval(timer) }, [attempt.deadlineAt, submit])
  async function choose(optionId: string) { setQuestions((current) => current.map((item) => item.id === question.id ? { ...item, selectedOptionId: optionId } : item)); await onSave(question.id, optionId) }
  const answered = questions.filter((item) => item.selectedOptionId).length; const minutes = String(Math.floor(remaining / 60)).padStart(2, '0'); const seconds = String(remaining % 60).padStart(2, '0')
  return <Card className="overflow-hidden"><div className="sticky top-0 flex items-center justify-between bg-primary px-5 py-3 text-white"><span className="flex items-center gap-2 text-sm font-semibold"><Clock3 />Thời gian còn lại</span><span className="text-xl font-bold tabular-nums">{minutes}:{seconds}</span></div><CardHeader><div className="flex items-center justify-between text-sm"><span className="font-semibold text-primary">Câu {index + 1} / {questions.length}</span><span className="text-muted-foreground">Đã trả lời {answered}/{questions.length}</span></div><CardTitle className="pt-3 text-xl leading-8">{question.text}</CardTitle></CardHeader><CardContent><fieldset className="flex flex-col gap-3"><legend className="sr-only">Chọn một đáp án</legend>{question.options.map((option) => <label key={option.id} className={`flex min-h-14 cursor-pointer items-center gap-3 rounded-md border p-4 text-sm font-medium transition-colors ${question.selectedOptionId === option.id ? 'border-primary bg-blue-50 text-primary' : 'hover:bg-muted'}`}><input type="radio" name={question.id} checked={question.selectedOptionId === option.id} onChange={() => choose(option.id)} className="size-5" />{option.text}</label>)}</fieldset><div className="mt-8 flex items-center justify-between gap-3"><Button variant="outline" onClick={() => setIndex((value) => Math.max(0, value - 1))} disabled={index === 0}><ChevronLeft />Trước</Button>{index < questions.length - 1 ? <Button onClick={() => setIndex((value) => Math.min(questions.length - 1, value + 1))}>Tiếp<ChevronRight /></Button> : <Button onClick={() => setConfirm(true)}>Nộp bài</Button>}</div></CardContent><Dialog open={confirm} onOpenChange={setConfirm}><DialogContent className="max-w-md"><DialogHeader><DialogTitle>Xác nhận nộp bài</DialogTitle><DialogDescription>Bạn đã trả lời {answered}/{questions.length} câu. Các câu chưa trả lời sẽ được tính 0 điểm.</DialogDescription></DialogHeader><DialogFooter><Button variant="outline" onClick={() => setConfirm(false)}>Tiếp tục làm</Button><Button onClick={() => submit(false)} disabled={submitting}>{submitting ? <LoaderCircle className="animate-spin" /> : null}Xác nhận nộp</Button></DialogFooter></DialogContent></Dialog></Card>
}
function ResultScreen({ attempt, state, onRetry, onHome }: { attempt: Attempt; state: LearnerState; onRetry: () => void; onHome: () => void }) {
  const passed = Boolean(attempt.passed); const canRetry = state.canStart && !state.activeAttemptId && state.attemptsRemaining > 0
  return <div className="flex flex-col gap-5"><Card><CardContent className="flex flex-col items-center p-8 text-center">{passed ? <CheckCircle2 className="size-20 text-emerald-600" /> : <XCircle className="size-20 text-red-600" />}<h1 className={`mt-4 text-4xl font-extrabold ${passed ? 'text-emerald-700' : 'text-red-700'}`}>{passed ? 'ĐẠT' : 'CHƯA ĐẠT'}</h1><p className="mt-2 text-3xl font-bold">{formatScore(attempt.scorePercent).replace('%', ' điểm')}</p><p className="mt-3 text-sm text-muted-foreground">Lần làm {attempt.attemptNo}/{state.batch.maxAttempts} · {attempt.autoSubmitted ? 'Tự động nộp khi hết giờ' : 'Đã nộp bài'}</p>{canRetry ? <Button size="lg" className="mt-6 w-full" onClick={onRetry}>Làm lại</Button> : null}<Button variant="outline" className="mt-3 w-full" onClick={onHome}>Về thông tin khóa học</Button></CardContent></Card>{attempt.reviewUnlocked ? <Card><CardHeader><CardTitle>Xem lại đáp án</CardTitle></CardHeader><CardContent className="flex flex-col gap-4">{attempt.questions.map((question) => { const selected = question.options.find((option) => option.id === question.selectedOptionId); const correct = question.options.find((option) => option.isCorrect); const right = selected?.id === correct?.id; return <div key={question.id} className="border-b pb-4 last:border-0"><p className="text-sm font-semibold text-primary">Câu {question.displayOrder}</p><p className="mt-1 font-medium">{question.text}</p><p className={`mt-2 text-sm ${right ? 'text-emerald-700' : 'text-red-700'}`}>Đáp án của bạn: {selected?.text ?? 'Chưa trả lời'}</p><p className="mt-1 text-sm">Đáp án đúng: {correct?.text}</p>{question.explanation ? <p className="mt-2 text-xs text-muted-foreground">{question.explanation}</p> : null}</div> })}</CardContent></Card> : <Card><CardContent className="p-5 text-sm text-muted-foreground">Đáp án đúng chưa được mở vì bạn vẫn còn quyền làm lại. Chi tiết chỉ hiển thị sau khi quy trình được khóa theo chính sách AFTER_FINAL_LOCK.</CardContent></Card>}</div>
}
