import { useMemo, useState } from 'react'
import { Archive, Pencil, Plus, Search } from 'lucide-react'
import { useData } from '@/data/data-context'
import type { Department, Employee } from '@/types/domain'
import { Button } from '@/components/ui/button'; import { Input } from '@/components/ui/input'; import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'; import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog'; import { PageHeader } from '@/components/shared/PageHeader'; import { EmptyState } from '@/components/ui/state'; import { Badge } from '@/components/ui/badge'
const blankEmployee = (): Employee => ({ id: crypto.randomUUID(), employeeCode: '', fullName: '', departmentId: null, positionName: '', email: '', isActive: true })
const blankDepartment = (): Department => ({ id: crypto.randomUUID(), departmentCode: '', departmentName: '', isActive: true })
export default function EmployeesPage() {
  const { data, upsert, archive } = useData(); const [query, setQuery] = useState(''); const [department, setDepartment] = useState(''); const [editing, setEditing] = useState<Employee | null>(null); const [editingDepartment, setEditingDepartment] = useState<Department | null>(null)
  const rows = useMemo(() => data.employees.filter((employee) => (!query || `${employee.employeeCode} ${employee.fullName}`.toLowerCase().includes(query.toLowerCase())) && (!department || employee.departmentId === department)), [data.employees, query, department])
  async function saveEmployee(event: React.FormEvent) { event.preventDefault(); if (!editing?.employeeCode.trim() || !editing.fullName.trim()) return; await upsert('employees', { ...editing, departmentName: data.departments.find((item) => item.id === editing.departmentId)?.departmentName }); setEditing(null) }
  async function saveDepartment(event: React.FormEvent) { event.preventDefault(); if (!editingDepartment?.departmentCode.trim() || !editingDepartment.departmentName.trim()) return; await upsert('departments', editingDepartment); setEditingDepartment(null) }
  return <><PageHeader title="Nhân viên & Phòng ban" description="Quản lý danh sách nhân sự được giao đào tạo." action={<div className="flex gap-2"><Button variant="outline" onClick={() => setEditingDepartment(blankDepartment())}><Plus />Phòng ban</Button><Button onClick={() => setEditing(blankEmployee())}><Plus />Nhân viên</Button></div>} /><Card><CardHeader><div className="flex flex-col gap-3 md:flex-row"><label className="relative flex-1"><Search className="absolute left-3 top-2.5 text-muted-foreground" /><Input className="pl-10" placeholder="Tìm mã hoặc họ tên" value={query} onChange={(event) => setQuery(event.target.value)} /></label><select className="h-10 rounded-md border bg-background px-3 text-sm" value={department} onChange={(event) => setDepartment(event.target.value)}><option value="">Tất cả phòng ban</option>{data.departments.filter((item) => item.isActive).map((item) => <option value={item.id} key={item.id}>{item.departmentName}</option>)}</select></div></CardHeader><CardContent className="overflow-x-auto p-0">{rows.length === 0 ? <EmptyState title="Không có nhân viên" description="Thử thay đổi bộ lọc hoặc thêm nhân viên mới." /> : <table className="data-table"><thead><tr><th>Mã NV</th><th>Họ tên</th><th>Phòng ban</th><th>Chức danh</th><th>Trạng thái</th><th>Thao tác</th></tr></thead><tbody>{rows.map((employee) => <tr key={employee.id}><td className="font-semibold">{employee.employeeCode}</td><td>{employee.fullName}</td><td>{employee.departmentName ?? '—'}</td><td>{employee.positionName || '—'}</td><td><Badge variant={employee.isActive ? 'success' : 'secondary'}>{employee.isActive ? 'Hoạt động' : 'Ngưng'}</Badge></td><td><div className="flex gap-1"><Button variant="ghost" size="icon" onClick={() => setEditing(employee)} aria-label={`Sửa ${employee.fullName}`}><Pencil /></Button>{employee.isActive ? <Button variant="ghost" size="icon" onClick={() => archive('employees', employee.id)} aria-label={`Lưu trữ ${employee.fullName}`}><Archive /></Button> : null}</div></td></tr>)}</tbody></table>}</CardContent></Card><Card className="mt-6"><CardHeader><CardTitle>Phòng ban</CardTitle></CardHeader><CardContent className="flex flex-wrap gap-2">{data.departments.map((item) => <button key={item.id} onClick={() => setEditingDepartment(item)}><Badge variant={item.isActive ? 'outline' : 'secondary'}>{item.departmentCode} — {item.departmentName}</Badge></button>)}</CardContent></Card>
  <Dialog open={Boolean(editing)} onOpenChange={(open) => !open && setEditing(null)}><DialogContent><DialogHeader><DialogTitle>{editing && data.employees.some((item) => item.id === editing.id) ? 'Sửa nhân viên' : 'Thêm nhân viên'}</DialogTitle><DialogDescription>Thông tin dùng để tìm và giao đào tạo.</DialogDescription></DialogHeader>{editing ? <form onSubmit={saveEmployee}><div className="form-grid mt-5"><label className="field"><span className="field-label">Mã nhân viên *</span><Input value={editing.employeeCode} onChange={(event) => setEditing({ ...editing, employeeCode: event.target.value })} /></label><label className="field"><span className="field-label">Họ tên *</span><Input value={editing.fullName} onChange={(event) => setEditing({ ...editing, fullName: event.target.value })} /></label><label className="field"><span className="field-label">Phòng ban</span><select className="h-10 rounded-md border bg-background px-3 text-sm" value={editing.departmentId ?? ''} onChange={(event) => setEditing({ ...editing, departmentId: event.target.value || null })}><option value="">Chưa chọn</option>{data.departments.filter((item) => item.isActive).map((item) => <option value={item.id} key={item.id}>{item.departmentName}</option>)}</select></label><label className="field"><span className="field-label">Chức danh</span><Input value={editing.positionName} onChange={(event) => setEditing({ ...editing, positionName: event.target.value })} /></label><label className="field md:col-span-2"><span className="field-label">Email</span><Input type="email" value={editing.email ?? ''} onChange={(event) => setEditing({ ...editing, email: event.target.value })} /></label></div><DialogFooter><Button type="button" variant="outline" onClick={() => setEditing(null)}>Hủy</Button><Button>Lưu nhân viên</Button></DialogFooter></form> : null}</DialogContent></Dialog>
  <Dialog open={Boolean(editingDepartment)} onOpenChange={(open) => !open && setEditingDepartment(null)}><DialogContent className="max-w-md"><DialogHeader><DialogTitle>Phòng ban</DialogTitle><DialogDescription>Mã phòng ban là duy nhất.</DialogDescription></DialogHeader>{editingDepartment ? <form onSubmit={saveDepartment}><div className="mt-5 flex flex-col gap-4"><label className="field"><span className="field-label">Mã phòng ban *</span><Input value={editingDepartment.departmentCode} onChange={(event) => setEditingDepartment({ ...editingDepartment, departmentCode: event.target.value })} /></label><label className="field"><span className="field-label">Tên phòng ban *</span><Input value={editingDepartment.departmentName} onChange={(event) => setEditingDepartment({ ...editingDepartment, departmentName: event.target.value })} /></label></div><DialogFooter><Button type="button" variant="outline" onClick={() => setEditingDepartment(null)}>Hủy</Button><Button>Lưu</Button></DialogFooter></form> : null}</DialogContent></Dialog></>
}
