import { useState } from 'react'
import { Navigate, useLocation } from 'react-router-dom'
import { GraduationCap, LoaderCircle } from 'lucide-react'
import { z } from 'zod'
import { useAuth } from '@/features/auth/auth-context'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/ui/dialog'
const schema = z.object({ email: z.string().email('Email không hợp lệ'), password: z.string().min(1, 'Vui lòng nhập mật khẩu') })
export default function LoginPage() {
  const auth = useAuth(); const location = useLocation(); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const [resetOpen, setResetOpen] = useState(false); const [resetEmail, setResetEmail] = useState(''); const [resetNotice, setResetNotice] = useState('')
  if (auth.authenticated) return <Navigate to={(location.state as { from?: string } | null)?.from ?? '/admin'} replace />
  async function submit(event: React.FormEvent) { event.preventDefault(); const parsed = schema.safeParse({ email, password }); if (!parsed.success) { setError(parsed.error.issues[0].message); return } setBusy(true); setError(''); try { await auth.signIn(email, password) } catch (reason) { setError(reason instanceof Error ? reason.message : 'Đăng nhập thất bại') } finally { setBusy(false) } }
  async function sendReset(event: React.FormEvent) { event.preventDefault(); const parsed = z.string().email('Email không hợp lệ').safeParse(resetEmail); if (!parsed.success) { setResetNotice(parsed.error.issues[0].message); return } setBusy(true); setResetNotice(''); try { await auth.requestPasswordReset(parsed.data); setResetNotice('Nếu email tồn tại, hệ thống đã gửi liên kết đặt lại mật khẩu.') } catch (reason) { setResetNotice(reason instanceof Error ? reason.message : 'Không thể gửi email đặt lại mật khẩu.') } finally { setBusy(false) } }
  return <main className="grid min-h-screen place-items-center bg-slate-100 p-4"><Card className="w-full max-w-md"><CardHeader className="items-center text-center"><div className="mb-2 grid size-12 place-items-center rounded-lg bg-primary text-primary-foreground"><GraduationCap /></div><CardTitle className="text-2xl">TLP Training</CardTitle><CardDescription>Đăng nhập dành cho quản trị viên / người đào tạo</CardDescription></CardHeader><CardContent><form className="flex flex-col gap-4" onSubmit={submit}>{!auth.configured ? <p className="rounded-md bg-amber-50 p-3 text-sm text-amber-800" role="alert">Hệ thống chưa được kết nối Supabase. Vui lòng cấu hình biến môi trường trước khi đăng nhập.</p> : null}<label className="field"><span className="field-label">Email</span><Input type="email" value={email} onChange={(event) => setEmail(event.target.value)} autoComplete="email" disabled={!auth.configured} /></label><label className="field"><span className="field-label">Mật khẩu</span><Input type="password" value={password} onChange={(event) => setPassword(event.target.value)} autoComplete="current-password" disabled={!auth.configured} /></label>{error ? <p className="text-sm text-destructive" role="alert">{error}</p> : null}<Button size="lg" disabled={busy || !auth.configured}>{busy ? <LoaderCircle data-icon="inline-start" className="animate-spin" /> : null}Đăng nhập</Button><Button type="button" variant="ghost" disabled={!auth.configured} onClick={() => { setResetEmail(email); setResetNotice(''); setResetOpen(true) }}>Quên / đổi mật khẩu</Button></form></CardContent></Card><Dialog open={resetOpen} onOpenChange={setResetOpen}><DialogContent className="max-w-md"><DialogHeader><DialogTitle>Đặt lại mật khẩu</DialogTitle><DialogDescription>Nhập email quản trị. Hệ thống sẽ gửi một liên kết đặt mật khẩu mới.</DialogDescription></DialogHeader><form className="mt-5 flex flex-col gap-4" onSubmit={sendReset}><label className="field"><span className="field-label">Email</span><Input type="email" value={resetEmail} onChange={(event) => setResetEmail(event.target.value)} autoComplete="email" /></label>{resetNotice ? <p className="text-sm text-muted-foreground" role="status">{resetNotice}</p> : null}<Button disabled={busy}>{busy ? <LoaderCircle className="animate-spin" /> : null}Gửi liên kết đặt lại</Button></form></DialogContent></Dialog></main>
}
